sudo: required

language: go
go:
  - 1.8.1
  
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fuse
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go get -d -t -v ./...
  - go build -x -v ./...
  - go test -a -x -v ./...
  - go test -a -x -v -race ./...
  - diff <(gofmt -d .) <("")
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash .travis/test-coverage.sh; fi
